name: Deploy to Vercel

on:
  push:
    branches:
      - main       # trigger Preview deploy on push to main
    tags:
      - 'v*'       # trigger Production deploy on tags like v1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel project info
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel pull --yes --token=$VERCEL_TOKEN

      - name: Build
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel build --token=$VERCEL_TOKEN

      - name: Deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "🚀 Production deploy"
            vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
          else
            echo "👀 Preview deploy"
            vercel deploy --prebuilt --token=$VERCEL_TOKEN
          fi
