# .github/workflows/deploy.yml
name: Deploy to Vercel

on:
  push:
    branches:
      - main         # auto Preview deploys
  workflow_dispatch:  # manual trigger for Production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel project config
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel pull --yes --token=$VERCEL_TOKEN

      - name: Build
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel build --token=$VERCEL_TOKEN

      - name: Deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [[ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]]; then
            echo "🚀 Manual Production Deploy"
            vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
          else
            echo "👀 Auto Preview Deploy"
            vercel deploy --prebuilt --token=$VERCEL_TOKEN
          fi
