name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get commit message
        id: commit
        run: echo "message=$(git log -1 --pretty=%B)" >> "$GITHUB_OUTPUT"

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Pull Vercel project config
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel pull --yes --token=$VERCEL_TOKEN

      - name: Build
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" || "${{ steps.commit.outputs.message }}" == *"#prod"* ]]; then
            echo "🏗️ Building for Production"
            vercel build --prod --token=$VERCEL_TOKEN
          else
            echo "🏗️ Building for Preview"
            vercel build --token=$VERCEL_TOKEN
          fi

      - name: Deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" || "${{ steps.commit.outputs.message }}" == *"#prod"* ]]; then
            echo "🚀 Auto Production Deploy (from commit)"
            vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
          else
            echo "👀 Preview Deploy"
            vercel deploy --prebuilt --token=$VERCEL_TOKEN
          fi
